Handle both SQL BLOB and CLOB types
googlegsa/database pull request #10
Opened 2017-05-10 16:36 UTC by srinicodebytes

Fix b/25753195. BLOB mode in v4 should explicitly handle both
SQL BLOB and CLOB types.

2017-05-11 02:04 UTC, wiarlawd requested changes
Partial review. I didn't get to the last block of tests, and would like to see a cleaned up version before I got over the tests in more detail.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +        int columnType = rsMetaData.getColumnType(i);
Apropos of nothing?

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +        log.log(Level.FINEST, "Column name: {0}, Type: {1}", new Object[] {columnName, columnType});
80 cols, here, there, and everywhere.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
>    public static ResponseGenerator blobColumn(Map<String, String> config) {
Add @deprecated tag and @Deprecated annotation.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +      int columnType = Types.OTHER;
Since this is what you want, putting it second among these declarations makes no sense. I would typically pick first.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          log.log(Level.FINEST, "Name: {0}, Type: {1}", new Object[] {columnName, columnType});
s/Name/Content column name/

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        if (columnName.equals(getContentColumnName())) {
Case-sensitivity issues. Plus if you don't find it in the list you just blithely proceed, which doesn't make a lot of sense to me. Use ResultSet.findColumn instead, and just bail if it fails.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          in = new ByteArrayInputStream(CharStreams.toString(rd).getBytes(Charsets.UTF_8));
Use OutputStreamWriter

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          clob = rs.getClob(getContentColumnName());
No can do. LONGVARCHAR should call rs.getCharacterStream.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          blob = rs.getBlob(getContentColumnName());
And LONGVARBINARY should call rs.getBinaryStream.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          Reader rd2 = rs.getNCharacterStream(getContentColumnName());
Split out NCLOB to call getNClob. I don't think I've ever seen one of those in the wild.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        com.google.enterprise.adaptor.IOHelper.copyStream(in, out);
Import IOHelper.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +      } catch (java.sql.SQLFeatureNotSupportedException
More exceptions are possible. I've gotten NoSuchMethodException or NoSuchMethodError, I can't remember which, and generic SQLExceptions are certainly possible as well. I would just catch Exception, and log it at FINE.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            clob.free();
Just clean these up in-place above. It will make the code a little longer, but I think it will be more clear.

2017-05-11 02:04 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +                return new javax.sql.rowset.serial.SerialClob(c);
import

2017-05-11 02:04 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    ArrayList<String> names = new ArrayList<String>(Arrays.asList("my-blob-col"));
Why are you copying these lists?

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          break;
This should explicitly log a failure, not just silently happen.

Maybe add TODO here to try other things, or just let that come up naturally with BFILE.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          in = new ByteArrayInputStream(CharStreams.toString(rd).getBytes(Charsets.UTF_8));
It's standard practice to statically import UTF_8.

2017-05-11 02:04 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          Reader rd = rs.getCharacterStream(getContentColumnName());
rd can be null here. Check the other column values as well.

2017-05-11 02:04 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    ArrayList<String> names = new ArrayList<String>(Arrays.asList("my-blob-col"));
Static import for asList.

2017-05-11 02:04 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    char c[] = content.toCharArray();
What benefit is the char array playing here over passing the string to makeMockClobResultSet? If it's just for SerialClob's benefit, don't pollute the callers with that implementation detail.

2017-05-11 02:04 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  private ResultSet makeMockBlobResultSet(final byte b[], final ArrayList<String> names,
Scrap the added "final" when you don't need them. Don't delete any existing ones, but this practice is "not favored".

2017-05-12 01:27 UTC, srinicodebytes reviewed
Please review the changes.

2017-05-12 02:12 UTC, wiarlawd requested changes

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          writer = new OutputStreamWriter(resp.getOutputStream(), CHARSET);
The OutputStreamWriter was meant to be used in place of CharStreams.toString.

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +  private static final Charset CHARSET = Charset.forName("UTF-8");
import static com.google.common.base.Charsets.UTF_8;

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.write(rs.getString(getContentColumnName()));
Could be null

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.write(rs.getBytes(getContentColumnName()).toString());
Calling toString on a byte array? Also, could be null.

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          Clob clob = rs.getClob(getContentColumnName());
Could be null

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          NClob nclob = rs.getNClob(getContentColumnName());
Could be null

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          clob.free();
Use a finally block (on the try-with-resources when feasible) to free the LOBs. What happened to catching Exceptions around free?

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          Blob blob = rs.getBlob(getContentColumnName());
Could be null

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.write(rs.getString(getContentColumnName()));
Could be null

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          log.log(Level.FINEST, "Clumn type not handled: {0}",
s/Clumn/Column/

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +              new Object[] {columnType});
Don't need an Object[] for a single argument.

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          rs.findColumn(getContentColumnName()));
You could (maybe should?) keep this and use the index in place of getContentColumnName() in the getters below.

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          if (writer != null) {
???

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          if (reader != null) {
Won't be null

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          if (reader != null) {
Won't be null

2017-05-12 02:12 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +            }
throw new SQLException

2017-05-12 02:12 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +            }
throw new SQLException

2017-05-12 02:12 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    return makeMockBlobResultSet(b, new ArrayList<String>(), new ArrayList<Integer>());
80 cols

2017-05-12 02:12 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    return makeMockClobResultSet(s, new ArrayList<String>(), new ArrayList<Integer>());
80 cols

2017-05-12 02:12 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +        ResultSetMetaData.class.getClassLoader(), new Class[] { ResultSetMetaData.class },
80 cols

2017-05-12 02:12 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.close();
Use try-with-resources to close streams, and note that it's OK for the stream to be null (though you still need to check it in the body before you use it).

2017-05-12 22:12 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +  private static final Charset CHARSET = Charset.forName("UTF-8");
done

2017-05-12 22:13 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          log.log(Level.FINEST, "Clumn type not handled: {0}",
done

2017-05-12 22:13 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +              new Object[] {columnType});
done

2017-05-12 22:14 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    return makeMockBlobResultSet(b, new ArrayList<String>(), new ArrayList<Integer>());
done

2017-05-12 22:14 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +            }
done

2017-05-12 22:14 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    return makeMockClobResultSet(s, new ArrayList<String>(), new ArrayList<Integer>());
done

2017-05-12 22:14 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +            }
done

2017-05-12 22:14 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +        ResultSetMetaData.class.getClassLoader(), new Class[] { ResultSetMetaData.class },
done

2017-05-12 22:25 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          rs.findColumn(getContentColumnName()));
done

2017-05-13 02:44 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.write(rs.getString(getContentColumnName()));
done

2017-05-13 02:44 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.close();
done

2017-05-13 02:45 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +            writer.write(rs.getBytes(getContentColumnName()).toString());
done

2017-05-13 02:45 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          Clob clob = rs.getClob(getContentColumnName());
Done, as discussed

2017-05-13 02:45 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          if (reader != null) {
done

2017-05-13 02:45 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          clob.free();
done

2017-05-13 02:45 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          NClob nclob = rs.getNClob(getContentColumnName());
done

2017-05-13 02:45 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          if (reader != null) {
done

2017-05-13 02:46 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          Blob blob = rs.getBlob(getContentColumnName());
done, as discussed

2017-05-13 21:48 UTC, wiarlawd requested changes
Partial review. Still have to look at the tests.

Much nicer, thanks.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +import com.google.common.io.CharStreams;
Unused

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +import java.io.ByteArrayInputStream;
Unused

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +  @Deprecated
Add a javadoc tag as well: Use {@link #contentColumn contentColumn}

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.VARBINARY:
VARBINARY should use getBytes.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          clob.free();
Move to finally block on the try, and catch and log Exception.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          nclob.free();
Move to finally block on the try, and catch and log Exception.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
>            blob.free();
Move to finally block on the try, and catch and log Exception.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.NCHAR:
NCHAR and NVARCHAR should move to the block below that uses getString.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.LONGNVARCHAR:
Move this up after LONGVARCHAR.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +      char buffer[] = new char[1024];
Move [] to after char (style violation).

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +      char buffer[] = new char[1024];
Use a bigger block size. IOHelper.copyStream uses 8192.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +      while ((len = reader.read(buffer, 0, 1024)) != -1) {
s/, 0, 1024//

This is needed on the write, but on reads we can just fill the buffer.

2017-05-13 21:48 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
>      }
Call writer.flush, since IOHelper.copyStream does.

2017-05-15 21:20 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +      final List<String> names, final List<Integer> types) {
These need final as they are used by inner class (in Java 1.7 ).

2017-05-16 00:39 UTC, wiarlawd requested changes
Complete review this time.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +  @Deprecated
/** @deprecated Use {@link #contentColumn contentColumn} */
@Deprecated
public static ResponseGenerator blobColumn(...

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +          try (ByteArrayInputStream in =
No BAIS, just out.write(bytes), and you're not checking for null.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +              } catch (java.sql.SQLFeatureNotSupportedException
Just catch Exception, as previously discussed. Some drivers will throw other exceptions here.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +                // let JVM garbage collection deal with it
Let's just drop this comment for brevity, since this block appears 3 times.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +                log.log(Level.FINEST, "Error closing clob", unsupported);
Choose between a Java reference and a SQL reference: Clob or CLOB, but not clob. Same elsewhere.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +              if (reader != null) {
Delete this check. I don't think it can happen, and we're not checking in the other two LOBs.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.LONGVARCHAR:
The order here is kind of random. Let's put like together with like, and in something like the order most likely to be used: BLOB, CLOB, NCLOB, LONGVARBINARY, LONGVARCHAR, LONGNVARCHAR, BINARY + VARBINARY, string, default.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.VARBINARY:
Treat BINARY the same as VARBINARY.

2017-05-16 00:39 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.SMALLINT:
List in a logical order, and BIGINT and REAL are missing: integers by size, floats by size, chars (as-is).

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +                  names.get(((Integer)args[0]).intValue() - 1))) {
Add space after cast.

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +              for (int i = 0; i < names.size(); i++) {
Could just write:

int index = names.indexOf(args[0]) + 1;
if (index == 0) { throw new SQLException(...); }

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  private ResultSet makeMockClobResultSet(String s) {
This is never used.

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  private ResultSet makeMockBlobResultSet(byte b[]) {
This is never used.

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  private ResultSetMetaData makeMockResultSetMetaData(final List name,
s/name/names/, s/type/types/

Lists of what?

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +                  names.get(((Integer)args[0]).intValue() - 1))) {
Add space after cast.

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    ResponseGenerator.contentColumn(Collections.<String, String>emptyMap());
Something should call blobColumn (preferably without thrown an exception, though). Maybe add a single test that asserts that blobColumn(...).getClass().getName() equals "com.google.enterprise.adaptor.database.ContentColumn"?

2017-05-16 00:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +        makeMockClobResultSet(content, asList("my-col-name-is-wrong"),
Why are you passing the wrong column name to the mock as well?

2017-05-16 20:27 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.LONGVARCHAR:
done

2017-05-17 06:25 UTC, wiarlawd requested changes
The end is near.

2017-05-17 06:25 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +import java.io.ByteArrayInputStream;
Unused

2017-05-17 06:25 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.TINYINT:
As discussed, let's drop the integer types, at least for now. For posterity, we're also not handling dates and structured types here. The content must be of a binary or character type.

2017-05-17 06:25 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +import java.util.ArrayList;
Unused

2017-05-17 06:25 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +              for (int i = 0; i < names.size(); i++) {
Bump; you updated the mock findColumn for BLOBs but not this one.

2017-05-17 19:42 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +import java.io.ByteArrayInputStream;
done

2017-05-17 19:42 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +        case Types.TINYINT:
done

2017-05-17 19:42 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +import java.util.ArrayList;
done

2017-05-17 19:42 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +              for (int i = 0; i < names.size(); i++) {
Thanks, missed it. done.

2017-05-19 00:18 UTC, wiarlawd approved these changes
LGTM, with a nit.

2017-05-19 00:18 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +                copy(reader, writer);
Unindent two spaces.

2017-05-19 00:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/ResponseGenerator.java
> +                copy(reader, writer);
done

2017-05-19 00:41 UTC, merged