Add tests for getDocIds, getDocContent
googlegsa/database pull request #31
Opened 2017-05-25 02:21 UTC by srinicodebytes

- Changes to addMetaData method
- Tests for getDocIds and getDocContent

2017-05-25 05:29 UTC, wiarlawd requested changes
A lot of nits, but nothing major.

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private interface MetaDataHandler {
s/MetaData/Metadata/g

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    DocIdPusher.Record.Builder builder;
private final

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    public void addMetadata(String k, String v) throws SQLException;
s/public// (it's redundant in an interface)
s/throws SQLException//g (no implementations throw SQLException)

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private void addMetadada(MetaDataHandler meta, ResultSet rs)
s/Metadada/Metadata/

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    Response resp;
private final

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    BuilderMetadata metaData = new BuilderMetadata(builder);
Inline this.

2017-05-25 05:29 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +      RecordMetadata metaData = new RecordMetadata(resp);
Inline this.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/AccumulatingDocIdPusher.java
> +// Copyright 2012 Google Inc. All Rights Reserved.
I had a second thought here. Copy RecordingDocIdPusher and RecordingResponse from the library master instead. The MockRequest is fine.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +
Delete these added blank lines.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +        "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DEFAULT_ESCAPE=");
Add a public constant URL in JdbcFixture.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +        + "ID" + " integer,"
Eliminate these string concatenations and inline this method (yeah, twice).

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    executeUpdate("create table employees("
Please match the other tables (see ResponseGeneratorTest) and just do something like
"create table data (id int, name varchar)". The extra column isn't adding value.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    configEntries.put("db.singleDocContentSqlParameters", "ID");
Most of the rest of these are unnecessary. I'd pick rowToText or contentColumn, which require less configuration.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    final Config config = createStandardConfig(configEntries);
Is final needed?

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +
Delete blank line, or move it before pusher.getRecords.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    ImmutableList.Builder<Record> builder = ImmutableList.builder();
Import java.util.Arrays.asList and use that instead.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals(1, actual.size());
Delete this.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals(expected, actual);
Inline one or both of these, to give a better of idea of what's being compared.

2017-05-25 05:29 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals("col1", adaptor.metadataColumns.getMetadataName("ID"));
Why a different set of assertions here compared to the other test? I like the other one better.

2017-05-25 05:33 UTC, wiarlawd commented
Change the summary to something like "Combine addMetadata code blocks". If we want to call out adding the tests, we should just add them in a separate CL, but I don't think that's necessary. We're doing some refactoring, and adding tests in support of that.

2017-05-25 19:38 UTC, srinicodebytes reviewed
Changes as per review

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    public void addMetadata(String k, String v) throws SQLException;
done

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private interface MetaDataHandler {
done

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    DocIdPusher.Record.Builder builder;
done

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    Response resp;
done

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private void addMetadada(MetaDataHandler meta, ResultSet rs)
Thx, done

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    BuilderMetadata metaData = new BuilderMetadata(builder);
done

2017-05-25 19:38 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +      RecordMetadata metaData = new RecordMetadata(resp);
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +        "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DEFAULT_ESCAPE=");
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    final Config config = createStandardConfig(configEntries);
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals(1, actual.size());
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    ImmutableList.Builder<Record> builder = ImmutableList.builder();
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals(expected, actual);
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals("col1", adaptor.metadataColumns.getMetadataName("ID"));
removed these assertions

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    executeUpdate("create table employees("
removed extra column

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +        + "ID" + " integer,"
done

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    configEntries.put("db.singleDocContentSqlParameters", "ID");
This test needs urlAndMetadataLister. The next test uses rowTotext. Agree that less config is better. But found that these are required.

2017-05-25 19:38 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/AccumulatingDocIdPusher.java
> +// Copyright 2012 Google Inc. All Rights Reserved.
done

2017-05-25 21:42 UTC, wiarlawd requested changes
Some missed comments and clarifications.

2017-05-25 21:42 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private class BuilderMetadata implements MetadataHandler {
Sorry, I missed this earlier: s/Builder/Record/

2017-05-25 21:42 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private class RecordMetadata implements MetadataHandler {
s/Record/Response/

2017-05-25 21:42 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    ResultSetMetaData rsMetadata = rs.getMetaData();
I would not have said this change was worth touching every line for.

2017-05-25 21:42 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    executeUpdate("create table data(ID  integer, NAME  varchar)");
Inline this code in the callers.

2017-05-25 21:42 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    configEntries.put("db.singleDocContentSqlParameters", "ID");
Ah sorry about the mode, yeah.

I don't believe that these could all be required, though. Both the *Parameters values default to the names from db.uniqueKey, for example,  and db.singleDocContentSql only has to be present and empty; the query is never executed. The adaptor.namespace has a default value of "Default". displayUrlCol is not required.

2017-05-25 21:42 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +        Arrays.asList(new Record.Builder(new DocId("1001")).setMetadata(
Break before .setMetadata.

2017-05-25 21:42 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals("1001", response.getMetadata().getOneValue(adaptor.metadataColumns
What I was asking is why this test has a completely different set of assertions on the metadata from the getDocIds test. That is, why not just build an expected Metadata object here and assert that it matches response.getMetadata()?

2017-05-25 21:42 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +
Not done. Please delete blank lines in the non-static imports. This file was following the new style rules.

2017-05-25 23:53 UTC, wiarlawd approved these changes
Brett and I made some changes to use anonymous inner classes. Let me know what you think.

2017-05-25 23:58 UTC, srinicodebytes reviewed
LGTM

2017-05-25 23:58 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private class RecordMetadata implements MetadataHandler {
done

2017-05-25 23:58 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +  private class BuilderMetadata implements MetadataHandler {
done

2017-05-25 23:58 UTC, srinicodebytes commented on src/com/google/enterprise/adaptor/database/DatabaseAdaptor.java
> +    ResultSetMetaData rsMetadata = rs.getMetaData();
Keeping as is, since changed already

2017-05-25 23:58 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    executeUpdate("create table data(ID  integer, NAME  varchar)");
done

2017-05-25 23:58 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +        Arrays.asList(new Record.Builder(new DocId("1001")).setMetadata(
done

2017-05-25 23:58 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    assertEquals("1001", response.getMetadata().getOneValue(adaptor.metadataColumns
done

2017-05-25 23:58 UTC, srinicodebytes commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    configEntries.put("db.singleDocContentSqlParameters", "ID");
Tried changing some, db.uniqueKey seems to be required, same with adaptor.namespace. Ran into invalidConfigurationException. Removed displayUrlCol, and changed singleDocContentSql and singleDocContentSqlParameters to empty

2017-05-25 23:59 UTC, srinicodebytes reviewed
LGTM

2017-05-26 00:03 UTC, wiarlawd commented
I played around with the config properties. It looks like the createStandardConfig method is interfering with the normal adaptor behaviors. We do worry about that separately.

2017-05-26 00:09 UTC, merged