Use reasonable defaults in DBAT.createStandardConfig()
googlegsa/database pull request #38
Opened 2017-05-27 19:44 UTC by BrettMichaelJohnson

2017-05-27 20:41 UTC, wiarlawd requested changes
I said I was going to do this, and I don't know how badly it conflicts with #39, which I just put up.

2017-05-27 20:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    moreEntries.put("db.includeAllColumnsAsMetadata", "false");
Add a TODO that we should add a "Default_mcBlank" variation once we're using initConfig.

2017-05-27 20:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    configEntries.put("db.uniqueKey", "id:int");
I don't like having "real" defaults here. Having all these fake ones was bad enough, but it's now easy for tests to pass with implicit config, and so the tests are less self-contained. The ones that match initConfig are not a problem (most of the ones from includeAllColumnsAsMetadata down, I think).

2017-05-27 20:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +  // TODO(bmj): call initConfig() to set defaults for most properties.
Did you look into this? We're already calling initConfig here. We could easily statically import setConfigValue from TestHelper, and replace moreEntries.put with setConfigValue without much verbosity.

2017-06-01 00:44 UTC, wiarlawd reviewed
You should pull in master (again, sorry), to get Sri's change, which adds a half-dozen tests at the end.

I think it's just the Parameters and adaptor.namespace that can be deleted in most places.

2017-06-01 00:44 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +  private DatabaseAdaptor getObjectUnderTest(
Can we put these someplace logical, like before the first test, or at least before the first test that uses a DatabaseAdaptor instance?

2017-06-01 00:44 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +          new UserPrincipal("duser2")))
Undo whitespace change (reindent +2 columns)

2017-06-01 01:32 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    moreEntries.put("db.includeAllColumnsAsMetadata", "false");
done.

2017-06-01 01:32 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +          new UserPrincipal("duser2")))
Done.

2017-06-01 02:39 UTC, wiarlawd approved these changes
LGTM, with nits. Also, maybe update the commit message, perhaps "Use initConfig and its defaults in DatabaseAdaptorTest."

Very happy to see this change go in.

2017-06-01 02:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +import com.google.enterprise.adaptor.Principal;
Unused

2017-06-01 02:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +  private File writeConfig(Map<String, String> config) throws IOException {
I'm tempted to inline this as a third block in the middle, and save half the lines here.

2017-06-01 02:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
>      moreEntries.put("db.singleDocContentSqlParameters", "not_id");
Delete

2017-06-01 02:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
>      moreEntries.put("db.aclSqlParameters", "not_id");
Delete

2017-06-01 02:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    moreEntries.put("db.uniqueKey", "table_col:int");
This table (\"must be set\", table_col) was a paean to createStandardConfig. I think copying the table, db.uniqueKey, and db.singleDocContentSql from _metadataColumns, just above, would be an improvement.

2017-06-01 02:39 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    moreEntries.put("db.uniqueKey", "not_id:int");
Was not_id here and in the test below intentional? Because it doesn't matter, since we're suppressing query column verification?

2017-06-01 19:01 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +import com.google.enterprise.adaptor.Principal;
Done.

2017-06-01 19:01 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +  private File writeConfig(Map<String, String> config) throws IOException {
Done.

2017-06-01 19:01 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
>      moreEntries.put("db.singleDocContentSqlParameters", "not_id");
Done.

2017-06-01 19:01 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
>      moreEntries.put("db.aclSqlParameters", "not_id");
Done.

2017-06-01 19:01 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    moreEntries.put("db.uniqueKey", "table_col:int");
Done.

2017-06-01 19:01 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/DatabaseAdaptorTest.java
> +    moreEntries.put("db.uniqueKey", "not_id:int");
It was to have *some* uniqueKey specified, otherwise the test fails with missing uniqueKey.

2017-06-01 20:45 UTC, wiarlawd approved these changes
LGTM again? ;-)

2017-06-01 22:20 UTC, merged