Improve code coverage for ResponseGenerator
googlegsa/database pull request #62
Opened 2017-06-06 22:39 UTC by BrettMichaelJohnson

This brings coverage of ResponseGenerator up from 74% to 82%.
It will be difficult to do much better than this, since H2 does not
support LONGVARCHAR, LONGVARBINARY, or any of the 'N' character
types.

2017-06-07 02:35 UTC, wiarlawd requested changes
Mostly I don't like the methods names. I didn't like them before, but I don't like them now, either.

Are you planning to reorder the tests in a separate CL?

Including the actual captured messages on assert failures is the only substantive change.

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testRowToText_specialCharacters() throws Exception {
If this is the one-and-only rowToText test, why decorate the name?

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeServesResultVarchar() throws Exception {
What about dropping the verbosity of these names: testContentColumn_varchar, etc?

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String content = "hello world";
Unused

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeNullContent() throws Exception {
nullVarchar?

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeIncorrectColumnName() throws Exception {
Incorrect column names don't happen per-type (unlike nulls, say).

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeNullBinaryContent() throws Exception {
varbinary or binary?

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String content = "hello world";
Unused, Imma quit saying this.

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String content = "hello world";
Unused

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    assertEquals(1, messages.size());
s/1/messages.toString(), 1/g

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    assertEquals(null, bar.contentType);
s/assertEquals(null, /assertNull(/g? (The better error message here was fixed by JUnit 4.11.)

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String sql =
Join lines, plus other opportunities below. Not sure if they were on purpose or not.

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testRowToHtmlModeLoadsStyleSheet() throws Exception {
s/ModeLoadsStyleSheet/_stylesheet/

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testRowToHtmlModeFailsToLoadStyleSheet() throws Exception {
_stylesheetNotFound?

2017-06-07 02:35 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testBlobColumnModeContentTypeCol_nullValue() throws Exception {
These are also not per-type code. Also, maybe a naming convention to distinguish these from the test<Mode> tests, like testConfigContentTypeCol_null?

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testRowToText_specialCharacters() throws Exception {
Because I didn't know it was the only rowToText test, and it specifically tests the escaping of special characters.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeServesResultVarchar() throws Exception {
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeNullContent() throws Exception {
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentColumnModeNullBinaryContent() throws Exception {
done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String content = "hello world";
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String content = "hello world";
Thanks.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    assertEquals(1, messages.size());
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testBlobColumnModeContentTypeCol_nullValue() throws Exception {
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    String sql =
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +    assertEquals(null, bar.contentType);
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testRowToHtmlModeLoadsStyleSheet() throws Exception {
Done.

2017-06-07 23:47 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testRowToHtmlModeFailsToLoadStyleSheet() throws Exception {
Done.

2017-06-08 00:41 UTC, wiarlawd requested changes

2017-06-08 00:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> -  public void testFilepathColumnModeIncorrectColumnName() throws Exception {
Restore this test.

2017-06-08 00:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> -  public void testUrlColumnModeIncorrectColumnName() throws Exception {
Restore this test.

2017-06-08 00:41 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> +  public void testContentTypeColumn_contentTypeOverride() throws Exception {
The config property is "contentTypeCol", not "Column". These three tests are per-class specific, so I think these should actually retain the testContentColumn_ prefix, maybe testContentColumn_contentTypeConflict for this one? I'm happy to just add a TODO to add content type config tests for the others classes. (You did add a single contentTypeCol test for UrlColumn.)

2017-06-10 23:36 UTC, wiarlawd commented
Ping in case you just forgot to push a change or something.

2017-06-11 04:49 UTC, wiarlawd approved these changes

2017-06-11 05:15 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> -  public void testFilepathColumnModeIncorrectColumnName() throws Exception {
Done.

2017-06-11 05:15 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/database/ResponseGeneratorTest.java
> -  public void testUrlColumnModeIncorrectColumnName() throws Exception {
Done.

2017-06-11 05:16 UTC, merged